# Generated by Django 3.2.18 on 2023-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0170_auto_20230301_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisecustomer',
            name='org_id',
            field=models.CharField(blank=True, help_text='Enterprise Customer organization id', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalenterprisecustomer',
            name='org_id',
            field=models.CharField(blank=True, help_text='Enterprise Customer organization id', max_length=255, null=True),
        ),
    ]
